version: '2'

volumes:
  nextcloud:
  db:

services:
  db:
    image: mariadb:11.0.2-jammy
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=TheGibson
      - MYSQL_PASSWORD=TheGibson
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud

  nc:
    image: nextcloud:27.0.0-apache
    restart: always
    ports:
      - 8080:80
    links:
      - db
    volumes:
      - nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=TheGibson
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=db
