---
name: Nextcloud - MariaDB - Event - Firefox
author: Danilo Jesic <danilo@green-coding.berlin>
description: Installs the official Nextcloud image with a MariaDB and creates a calendar event. Uses a playwright script running Firefox to create an admin account, install the recommended apps and then create an event.
compose-file: !include compose-mariadb.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v12
    depends_on:
      nc:
        condition: service_healthy
#    volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode

flow:
  - name: Install Nextcloud
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/energy-tests/nextcloud_install.py firefox
        note: Installing Nextcloud
        read-notes-stdout: true
        log-stdout: true
        log-stderr: true

  - name: Login and create event
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/energy-tests/nextcloud_create_event.py firefox
        note: Creating event
        read-notes-stdout: true
        read-sci-stdout: true
        log-stdout: true
        log-stderr: true
