---
name: Nextcloud - MariaDB - Talk - Firefox
author: Danilo Jesic <danilo@green-coding.berlin>
description: Installs the official Nextcloud image with a MariaDB and starts a Talk conversation. Uses a playwright script running Firefox to create an admin account, install the recommended apps and then create a Talk conversation where guest users will send each other random text.
compose-file: !include compose-mariadb.yml

sci:
  R_d: Talk message

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v12
    depends_on:
      nc:
        condition: service_healthy
#    volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode

flow:
  - name: Talk conversation
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/energy-tests/nextcloud_talk.py firefox
        note: Starting conversation
        read-notes-stdout: true
        read-sci-stdout: true
        log-stdout: true
        log-stderr: true
