version: '2'

volumes:
  nextcloud-data-sqlite:

services:
  nc:
    image: nextcloud:30.0.0-apache
    #build: # The build takes currently ~ 30 minutes which is far too long for daily testing
    #  context: ../29/fpm
    #  dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:80
    environment:
      SQLITE_DATABASE: owncloud2.db
    volumes:
      - nextcloud-data-sqlite:/var/www/html
    healthcheck:
      test: curl --fail --silent http://nc
      interval: "1h" # effectively turns repeated healthchecks during runtime off
      start_period: "60s"
      start_interval: "1s"
