---
name: Nextcloud - Postgres - Event - Chromium
author: Danilo Jesic <danilo@green-coding.berlin>
description: Installs the official Nextcloud image with a Postgres DB and creates a calendar event. Uses a playwright script running Chromium to create an admin account, install the recommended apps and then create a calendar event.
compose-file: !include compose-postgres.yml

services:
  gcb-playwright:
    image: greencoding/gcb_playwright:v12
    depends_on:
      nc:
        condition: service_healthy
#    volumes:
#       - /tmp/.X11-unix:/tmp/.X11-unix # for debugging in non-headless mode
    environment:
       DISPLAY: ":0" # for debugging in non-headless mode


flow:
  - name: Login and create event
    container: gcb-playwright
    commands:
      - type: console
        command: python3 /tmp/repo/energy-tests/nextcloud_create_event.py
        note: Creating event
        read-notes-stdout: true
        read-sci-stdout: true
        log-stdout: true
        log-stderr: true
